name: Build, Upload, and Sync

on:
  release:
    types: [ published ] # è‡ªåŠ¨è§¦å‘åŒæ­¥

jobs:
  build-and-sync:
    runs-on: ubuntu-latest

    steps:
      # è®¾ç½®æ—¶åŒºä¸ºäºšæ´²/ä¸Šæµ·
      - name: Set Timezone to Asia/Shanghai
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          echo "Current time: $(date)"

      # æ£€å‡ºä»£ç 
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # ç¼“å­˜ Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # è®¾ç½® JDK 17 //try one try?
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # è·å–åŸä»“åº“çš„é¢„å‘è¡Œç‰ˆå±æ€§
      - name: Get Original Repository Pre-release Property
        id: pre_release
        run: |
          echo "IS_PRERELEASE=$(if [ "${{ github.event.release.prerelease }}" = true ]; then echo 'true'; else echo 'false'; fi)" >> $GITHUB_OUTPUT

      # èµ‹äºˆ Gradlew æ‰§è¡Œæƒé™
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # åŒæ—¶ç¼–è¯‘ Normal å’Œ Compatible APK
      - name: Build Normal and Compatible APKs
        run: |
          ./gradlew assembleNormalRelease assembleCompatibleRelease -Pversion=${{ github.ref_name }}

      - name: Sign APKs from multiple directories
        id: sign_apks
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: |
            app/build/outputs/apk/compatible/release:
            app/build/outputs/apk/normal/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Split Signed Files
        id: split_files
        uses: jungwinter/split@v1
        with:
          msg: ${{ steps.sign_apks.outputs.signedReleaseFiles }}
          separator: ':'

      - name: Upload Normal APK to WebDAV
        uses: uetchy/upload-to-webdav-action@v1
        with:
          url: ${{ secrets.WEBDAV_URL }}/LanZou/Sesame-TK/
          username: ${{ secrets.WEBDAV_USERNAME }}
          password: ${{ secrets.WEBDAV_PASSWORD }}
          source: ${{ steps.split_files.outputs._1 }}

      - name: Upload Compatible APK to WebDAV
        uses: uetchy/upload-to-webdav-action@v1
        with:
          url: ${{ secrets.WEBDAV_URL }}/LanZou/Sesame-TK/
          username: ${{ secrets.WEBDAV_USERNAME }}
          password: ${{ secrets.WEBDAV_PASSWORD }}
          source: ${{ steps.split_files.outputs._0 }}

      - name: Generate APKS Checksum
        run: |
          sha256sum ${{ steps.split_files.outputs._1 }} > CHECKSUMS-Sesame-Normal-${{ github.event.release.tag_name || github.ref_name }}.sha256
          sha256sum ${{ steps.split_files.outputs._0 }} > CHECKSUMS-Sesame-Compatible-${{ github.event.release.tag_name || github.ref_name }}.sha256


      - name: Upload Assets to Source Release
        uses: softprops/action-gh-release@v2
        with:
          nanme: Sesame-${{ github.event.release.tag_name || github.ref_name }} # å‘å¸ƒçš„åç§°ã€‚é»˜è®¤ä¸ºæ ‡ç­¾åç§°
          files: |
            ${{ steps.split_files.outputs._1 }}
            ${{ steps.split_files.outputs._0 }}
            CHECKSUMS-Sesame-Normal-${{ github.event.release.tag_name || github.ref_name }}.sha256
            CHECKSUMS-Sesame-Compatible-${{ github.event.release.tag_name || github.ref_name }}.sha256
          tag_name: ${{ github.ref_name }}
          draft: false
          append_body: true
          generate_release_notes: true
          body: |
            > å¢™å†…æ›´æ–°åœ°å€[æˆ³è¿™é‡Œ](https://fansirs.lanzoue.com/b011kv6pwd) å¯†ç :`9527`

      - name: Sync Release to Target Repository
        uses: softprops/action-gh-release@v2
        with:
          repository: Xposed-Modules-Repo/fansirsqi.xposed.sesame # ç›®æ ‡ä»“åº“çš„æ‹¥æœ‰è€…å’Œä»“åº“åç§°
          nanme: Sesame-${{ github.event.release.tag_name || github.ref_name }} # å‘å¸ƒçš„åç§°ã€‚é»˜è®¤ä¸ºæ ‡ç­¾åç§°
          files: |
            ${{ steps.split_files.outputs._1 }}
            ${{ steps.split_files.outputs._0 }}
            CHECKSUMS-Sesame-Normal-${{ github.event.release.tag_name || github.ref_name }}.sha256
            CHECKSUMS-Sesame-Compatible-${{ github.event.release.tag_name || github.ref_name }}.sha256
          token: ${{ secrets.TARGET_REPO_PAT }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: ${{ steps.pre_release.outputs.IS_PRERELEASE }}
          append_body: false
          make_latest: true
          body: |
            ğŸ“¦ æœ¬ Release åŒæ­¥è‡ªæºä»“åº“ [Sesame-TK](https://github.com/${{ github.repository }})
            âœ¨ **æ›´æ–°å†…å®¹**:
            ${{ github.event.release.body || 'æ— æ›´æ–°è¯´æ˜' }}

      - name: TgBot Notification
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TG_CHAT_ID }}" \
          -d "text=ğŸ“¦ New Release [${{ github.event.release.tag_name }}](${{ github.event.release.html_url }}) Published! %0A%0A${{ github.event.release.body }}" \
          -d "parse_mode=Markdown"


