name: Build, Upload, and Sync

on:
  release:
    types: [published] # è‡ªåŠ¨è§¦å‘åŒæ­¥

jobs:
  build-and-sync:
    runs-on: ubuntu-latest

    steps:
      # è®¾ç½®æ—¶åŒºä¸ºäºšæ´²/ä¸Šæµ·
      - name: Set Timezone to Asia/Shanghai
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          echo "Current time: $(date)"

      # æ£€å‡ºä»£ç 
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      # è·å–åŸä»“åº“çš„é¢„å‘è¡Œç‰ˆå±æ€§
      - name: Get Original Repository Pre-release Property
        id: pre_release
        run: |
          echo "IS_PRERELEASE=$(if [ "${{ github.event.release.prerelease }}" = true ]; then echo 'true'; else echo 'false'; fi)" >> $GITHUB_OUTPUT

      # èµ‹äºˆ Gradlew æ‰§è¡Œæƒé™
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # åŒæ—¶ç¼–è¯‘ Normal å’Œ Compatible APK
      - name: Build Normal and Compatible APKs
        run: |
          ./gradlew assembleNormalRelease assembleCompatibleRelease -Pversion=${{ github.ref_name }}

      - name: Sign Normal APK
        id: sign_normal_apk
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: app/build/outputs/apk/normal/release/
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 34.0.0

      - name: Sign Compatible APK
        id: sign_compatible_apk
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: app/build/outputs/apk/compatible/release/
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 34.0.0

      - name: Generate APKS Checksum
        run: |
          sha256sum ${{ steps.sign_normal_apk.outputs.signedFile  }} > CHECKSUMS-Sesame-Normal-${{ github.event.release.tag_name || github.ref_name }}.sha256
          sha256sum ${{ steps.sign_compatible_apk.outputs.signedFile }} > CHECKSUMS-Sesame-Compatible-${{ github.event.release.tag_name || github.ref_name }}.sha256

      - name: Upload Assets to Source Release
        uses: softprops/action-gh-release@v2
        with:
          nanme: Sesame-${{ github.event.release.tag_name || github.ref_name }} # å‘å¸ƒçš„åç§°ã€‚é»˜è®¤ä¸ºæ ‡ç­¾åç§°
          files: |
            ${{ steps.sign_normal_apk.outputs.signedFile }}
            ${{ steps.sign_compatible_apk.outputs.signedFile }}
            CHECKSUMS-Sesame-Normal-${{ github.event.release.tag_name || github.ref_name }}.sha256
            CHECKSUMS-Sesame-Compatible-${{ github.event.release.tag_name || github.ref_name }}.sha256
          tag_name: ${{ github.ref_name }}
          draft: false
          append_body: true
          generate_release_notes: true
          body: |
            > ## ä¸‹è½½è¯´æ˜
              * Normal ä¸ºæ­£å¸¸ç‰ˆæœ¬,é€‚ç”¨äºAndroid 8.0åŠä»¥ä¸Šçš„ç³»ç»Ÿ
              * Compatible ä¸ºå…¼å®¹ç‰ˆæœ¬,é€‚ç”¨äºAndroid 7.0åŠä»¥ä¸‹çš„ç³»ç»Ÿ,æœ€ä½æ”¯æŒAndroid 5.1
            > ## å¢™å†…æ›´æ–°
              [æŠ—æäº‘-LanZou](https://fansirs.lanzoue.com/b011kv6pwd) å¯†ç :`9527`
              [Aliståˆ†æµ-LanZou](https://alist.798356.xyz/LanZou/Sesame-TK) å¯†ç :`9527`
              [Aliståˆ†æµ-ALiYun](https://alist.798356.xyz/AliYun/share/Sesame-TK) å¯†ç :`9527`

      - name: Sync Release to Target Repository
        uses: softprops/action-gh-release@v2
        with:
          repository: Xposed-Modules-Repo/fansirsqi.xposed.sesame # ç›®æ ‡ä»“åº“çš„æ‹¥æœ‰è€…å’Œä»“åº“åç§°
          nanme: Sesame-${{ github.event.release.tag_name || github.ref_name }} # å‘å¸ƒçš„åç§°ã€‚é»˜è®¤ä¸ºæ ‡ç­¾åç§°
          files: |
            ${{ steps.sign_normal_apk.outputs.signedFile }}
            ${{ steps.sign_compatible_apk.outputs.signedFile }}
            CHECKSUMS-Sesame-Normal-${{ github.event.release.tag_name || github.ref_name }}.sha256
            CHECKSUMS-Sesame-Compatible-${{ github.event.release.tag_name || github.ref_name }}.sha256
          token: ${{ secrets.TARGET_REPO_PAT }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: ${{ steps.pre_release.outputs.IS_PRERELEASE }}
          append_body: false
          make_latest: true
          body: |
            ğŸ“¦ æœ¬ Release åŒæ­¥è‡ªæºä»“åº“ [Sesame-TK](https://github.com/${{ github.repository }})
            âœ¨ **æ›´æ–°å†…å®¹**:
            ${{ github.event.release.body || 'æ— æ›´æ–°è¯´æ˜' }}

      - name: TgBot Notification & Upload
        run: |
          # å‘é€å¸¦æ–‡ä»¶çš„é€šçŸ¥æ¶ˆæ¯
          curl -F document=@${{ steps.sign_normal_apk.outputs.signedFile }} -F document=@${{ steps.sign_compatible_apk.outputs.signedFile }} -F document=@CHECKSUMS-Sesame-Normal-${{ github.event.release.tag_name || github.ref_name }}.sha256 -F document=@CHECKSUMS-Sesame-Compatible-${{ github.event.release.tag_name || github.ref_name }}.sha256 "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendDocument?chat_id=${{ secrets.TG_CHAT_ID }}&caption=ğŸ“¦ æ–°ç‰ˆæœ¬å‘å¸ƒ [${{ github.event.release.tag_name }}](${{ github.event.release.html_url }})%0A%0Aâœ¨ æ›´æ–°å†…å®¹ï¼š%0A${{ github.event.release.body }}%0A%0AğŸ”— ä¸‹è½½åœ°å€ï¼š%0A${{ github.event.release.html_url }}%0AæŠ—æäº‘ï¼šhttps://fansirs.lanzoue.com/b011kv6pwd å¯†ç ï¼š9527&parse_mode=Markdown"
